trigger:
- main


pool:
  vmImage: ubuntu-latest


stages:

- stage: BuildApps
  displayName: Build apps
  jobs:
  - job: BuildFrontendApp
    displayName: Build frontend app
    steps:
      - script: echo stage 1. job 1. script 1
        displayName: build front end step
      - script: echo job 1. script 2
        displayName: unit tests frontend
  - job: BuildBackendApp
    displayName: build Backend App
    steps:
      - script: echo stage 1. job 2. script 1
        displayName: build backend app
      - script: echo stage 1. job 2. script 2
        displayName: unit tests backend

- stage: DeployToDev
  dependsOn: BuildApps
  displayName: deploy to DEv env
  jobs:
    - job: DeployFrontendDev
      displayName: deploy frontend to dev 
      steps:
      - script: echo stage 2. job 1. script 1
        displayName: deploy frontend app to dev
    - job: DeployBackendDev
      displayName: deploy backend to dev
      steps:
      - script: echo stage 2. job 2. script 1
        displayName: deploy frontend to dev

- stage: DeployToQA
  displayName: deploy to QA
  pool:
    vmImage: 'macos-10.14'
  dependsOn:
  - BuildApps
  # - DeployToDev
  # - DeployProd
  jobs:
    - job: DeployFrontendToQA
      displayName: deploy frontend to QA 
      steps:
      - script: echo stage 4. job 1. script 1
        displayName: deploy frontend app to QA
    - job: DeployBackendDev
      displayName: deploy backend to QA
      steps:
      - script: echo stage 4. job 2. script 1
        displayName: deploy backend to QA

- stage: DeployProd
  displayName: deploy frontend to prod env
  dependsOn:
  - DeployToQA
  - DeployToDev
  condition: succeeded('DeployToDev')
  jobs:
  - job: DeployFrontendToProd
    displayName: deploy frontend to prod
    steps:
    - script: echo stage 3. job 1. script 1
      displayName: deploy frontend to prod, pool mac os
  - job: DeployBackendToProd
    displayName: deploy backend to prod
    steps:
    - script: echo stage 3. job 2. script 1, pool 'vs-2017-win2016'
      displayName: deploy backend to prod
    
      